from turtle import *
tl = list()
turtle_color = list()
for i in range(5):
   turtle_color.append('blue')
   turtle_color.append('orange')
   turtle_color.append('yellow')
   turtle_color.append('green')
   turtle_color.append('cyan')
   turtle_color.append('blue')
   turtle_color.append('purple')
turtle_color.append('pink')
t1 = Turtle()
t1.shape('turtle')
t1.begin_fill()
t1.color('red','pink')
t1.speed(100)
for j in range(36):
   for i in range(4):
      t1.right(90)
      t1.forward(40)
   t1.right(10)
   tl.append(Turtle())
   tl[j].speed(100)
   tl[j].right(10*j)
   tl[j].color(turtle_color[j])
   tl[j].forward(40)
t1.end_fill()
exitonclick()
